import os
from glob import glob
import subprocess
import sys


def ensure_detectron2():
    try:
        import detectron2  # noqa: F401
    except ImportError:
        subprocess.check_call([
            sys.executable,
            "-m",
            "pip",
            "install",
            "--no-build-isolation",
            "git+https://github.com/facebookresearch/detectron2.git",
        ])


ensure_detectron2()

import cv2
import json
import numpy as np
import gradio as gr
import spaces
import geopandas as gpd
from shapely.geometry import Polygon, MultiPolygon
from shapely.ops import unary_union
import torch

from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor
from detectron2 import model_zoo

# =====================================================================
# 1. LOAD MODEL & METADATA DYNAMICALLY
# =====================================================================
MODEL_WEIGHTS = "model_final.pth"
METADATA_FILE = "class_metadata.json"

# Load dynamic classes generated by your Kaggle training notebook
thing_classes = ["building", "road", "parcel_boundary", "vegetation"]

if os.path.exists(METADATA_FILE):
    with open(METADATA_FILE, "r") as f:
        meta = json.load(f)
        thing_classes = meta.get("thing_classes", thing_classes)

num_classes = len(thing_classes)

# Configure Detectron2 CPU Predictor
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_classes
cfg.MODEL.WEIGHTS = MODEL_WEIGHTS
cfg.MODEL.DEVICE = "cpu"  # Runs 100% on CPU without ZeroGPU daily quotas

predictor = DefaultPredictor(cfg) if os.path.exists(MODEL_WEIGHTS) else None

# Visualization Color Palette (BGR)
PALETTE = {
    0: (235, 76, 52),    # Building (Red)
    1: (241, 196, 15),   # Road (Yellow)
    2: (46, 204, 113),   # Boundary / Parcel (Green)
    3: (155, 89, 182),   # Vegetation (Purple)
    4: (52, 152, 219)    # Vacant Land (Blue)
}

SAMPLE_IMAGES = sorted(
    glob(os.path.join("proper samples", "*.png"))
    + glob(os.path.join("proper samples", "*.jpg"))
    + glob(os.path.join("proper samples", "*.jpeg"))
)


def select_sample(evt: gr.SelectData):
    sample_path = SAMPLE_IMAGES[evt.index]
    return sample_path, sample_path

# =====================================================================
# 2. INFERENCE & TOPOLOGICAL CLEANING ENGINE
# =====================================================================
def run_cadastral_pipeline(input_image, conf_threshold, min_area_filter, device):
    if predictor is None:
        return None, " Model weights (`model_final.pth`) not found. Upload the trained checkpoint to the Space repository.", None, None

    if input_image is None:
        return None, "Please upload a valid drone survey orthomosaic patch.", None, None

    # Standardize image array
    img_rgb = np.array(input_image)
    if img_rgb.ndim == 2:
        img_rgb = cv2.cvtColor(img_rgb, cv2.COLOR_GRAY2RGB)
    elif img_rgb.shape[-1] == 4:
        img_rgb = cv2.cvtColor(img_rgb, cv2.COLOR_RGBA2RGB)

    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    # 1. Detectron2 Inference
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = float(conf_threshold)
    cfg.MODEL.DEVICE = "cuda" if device == "GPU (ZeroGPU)" and torch.cuda.is_available() else "cpu"
    local_predictor = DefaultPredictor(cfg)
    outputs = local_predictor(img_bgr)

    instances = outputs["instances"].to("cpu")
    scores = instances.scores.numpy()
    pred_classes = instances.pred_classes.numpy()
    pred_masks = instances.pred_masks.numpy()

    raw_polygons, final_classes, final_confs = [], [], []

    # 2. Extract Contour Polygons from Binary Masks
    for i in range(len(scores)):
        mask = pred_masks[i].astype(np.uint8)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            if cv2.contourArea(cnt) < min_area_filter or len(cnt) < 3:
                continue

            poly = Polygon(cnt.reshape(-1, 2))
            if not poly.is_valid:
                poly = poly.buffer(0)

            if poly.area >= min_area_filter:
                raw_polygons.append(poly)
                cls_idx = int(pred_classes[i])
                cls_name = thing_classes[cls_idx] if cls_idx < len(thing_classes) else f"class_{cls_idx}"
                final_classes.append(cls_name)
                final_confs.append(float(scores[i]))

    if not raw_polygons:
        return img_rgb, "No cadastral features detected above the selected confidence threshold.", None, None

    # 3. Enforce Non-Overlapping Spatial Topology
    sorted_idx = np.argsort(final_confs)[::-1]
    clean_polygons, clean_classes, clean_confs = [], [], []
    occupied_space = Polygon()

    for idx in sorted_idx:
        cur_poly = raw_polygons[idx]
        cur_cls = final_classes[idx]
        cur_conf = final_confs[idx]

        if occupied_space.is_empty:
            clean_polygons.append(cur_poly)
            clean_classes.append(cur_cls)
            clean_confs.append(round(cur_conf, 3))
            occupied_space = cur_poly
        else:
            cleaned = cur_poly.difference(occupied_space)
            if not cleaned.is_empty and cleaned.area >= min_area_filter:
                if isinstance(cleaned, MultiPolygon):
                    cleaned = max(cleaned.geoms, key=lambda a: a.area)
                clean_polygons.append(cleaned)
                clean_classes.append(cur_cls)
                clean_confs.append(round(cur_conf, 3))
                occupied_space = unary_union([occupied_space, cleaned])

    # 4. Generate Visual Vector Overlay
    annotated = img_rgb.copy()
    overlay = img_rgb.copy()

    for poly, cls_name in zip(clean_polygons, clean_classes):
        pts = np.array(poly.exterior.coords, dtype=np.int32)
        cls_id = thing_classes.index(cls_name) if cls_name in thing_classes else 0
        color = PALETTE.get(cls_id, (50, 150, 250))

        cv2.fillPoly(overlay, [pts], color)
        cv2.polylines(annotated, [pts], True, color, 2)

    cv2.addWeighted(overlay, 0.40, annotated, 0.60, 0, annotated)

    # 5. Export GeoJSON and Attribute CSV
    parcel_ids = [f"CAD-PARCEL-{1000 + i}" for i in range(len(clean_polygons))]
    gdf = gpd.GeoDataFrame({
        "parcel_id": parcel_ids,
        "feature_type": clean_classes,
        "confidence": clean_confs,
        "area_px": [round(p.area, 2) for p in clean_polygons],
        "geometry": clean_polygons
    })

    geojson_path = "cadastral_parcels.geojson"
    csv_path = "cadastral_attributes.csv"
    gdf.to_file(geojson_path, driver="GeoJSON")
    gdf.drop(columns=["geometry"]).to_csv(csv_path, index=False)

    summary_text = f"""
    ### Extraction Analytics
    * **Extracted Features / Parcels:** {len(clean_polygons)}
    * **Topological Overlaps:** 0 (Enforced via Boolean Spatial Difference)
    * **Mean Delineation Confidence:** {np.mean(clean_confs):.2f}
    * **Total Segmented Surface:** {sum(gdf['area_px']):,.0f} px²
    * **Identified Classes:** {', '.join(set(clean_classes))}
    """

    return annotated, summary_text, geojson_path, csv_path


def run_cpu(input_image, conf_threshold, min_area_filter):
    return run_cadastral_pipeline(input_image, conf_threshold, min_area_filter, "CPU")


@spaces.GPU
def run_gpu(input_image, conf_threshold, min_area_filter):
    return run_cadastral_pipeline(input_image, conf_threshold, min_area_filter, "GPU (ZeroGPU)")


def run_selected_device(input_image, conf_threshold, min_area_filter, device):
    if device == "GPU (ZeroGPU)":
        return run_gpu(input_image, conf_threshold, min_area_filter)
    return run_cpu(input_image, conf_threshold, min_area_filter)

# =====================================================================
# 3. GRADIO USER INTERFACE
# =====================================================================
with gr.Blocks(theme=gr.themes.Soft(), title="AI Cadastral Mapping System") as demo:
    gr.HTML("""
    <style>
        .project-context { border: 1px solid #d4d4d8 !important; border-radius: 6px !important; background: #fafafa !important; }
        .project-context > .label-wrap { color: #27272a !important; font-weight: 600 !important; }
        .project-context .prose { color: #3f3f46 !important; }
        .team-section { border: 1px solid #d4d4d8; border-radius: 8px; padding: 20px; background: #fafafa; }
        .team-section h2 { margin: 0 0 6px; color: #18181b; }
        .team-intro { margin: 0 0 18px; color: #52525b; }
        .team-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }
        .team-member { border: 1px solid #e4e4e7; border-radius: 6px; padding: 14px; background: white; }
        .team-member strong { display: block; color: #18181b; margin-bottom: 5px; }
        .team-member span { display: block; color: #52525b; font-size: 0.9em; }
        @media (max-width: 700px) { .team-grid { grid-template-columns: 1fr; } }
        @media (prefers-color-scheme: dark) {
            .project-context { border-color: #52525b !important; background: #27272a !important; }
            .project-context > .label-wrap { color: #f4f4f5 !important; }
            .project-context .prose { color: #e4e4e7 !important; }
            .team-section { border-color: #52525b; background: #18181b; }
            .team-section h2 { color: #f4f4f5; }
            .team-intro { color: #a1a1aa; }
            .team-member { border-color: #3f3f46; background: #27272a; }
            .team-member strong { color: #f4f4f5; }
            .team-member span { color: #a1a1aa; }
        }
    </style>
    """)
    gr.Markdown("# Team Engineer | AI-Based Automated Cadastral Land Parcel Extraction")
    gr.Markdown("**SIH Problem Statement 26012** | Mask R-CNN Instance Segmentation & Spatial Vector Topology Engine")

    with gr.Accordion("Brief note, approach and novelty", open=False, elem_classes=["project-context"]):
        gr.Markdown("""
        **Purpose**

        This prototype turns drone or orthorectified imagery into a GIS-ready handoff for cadastral workflows. It combines instance segmentation, confidence filtering, polygon vectorization, and overlap cleanup so survey teams can review extracted features instead of tracing every boundary manually.

        **Implemented in this demo**

        - Mask R-CNN instance segmentation for the trained land-feature classes
        - CPU inference and an optional GPU (ZeroGPU) route
        - Confidence and minimum-area filtering
        - Non-overlapping polygon cleanup using Shapely
        - Visual overlays plus GeoJSON and CSV downloads

        **Next extensions**

        Georeferenced GeoTIFF support, comparison against existing parcel layers, low-confidence surveyor review, editable WebGIS layers, and feedback-driven retraining can build on these exported vector results.
        """)

    with gr.Row():
        with gr.Column(scale=1):
            input_img = gr.Image(type="pil", label="Upload Drone Orthomosaic Patch (JPG/PNG)")
            device_selector = gr.Radio(["CPU", "GPU (ZeroGPU)"], value="CPU", label="Inference Device")
            conf_slider = gr.Slider(minimum=0.30, maximum=0.95, value=0.65, step=0.05, label="Confidence Threshold")
            area_slider = gr.Slider(minimum=20, maximum=1000, value=100, step=20, label="Min Parcel Area Filter (px²)")
            submit_btn = gr.Button("Run Cadastral Delineation", variant="primary")

        with gr.Column(scale=1):
            output_img = gr.Image(type="numpy", label="Segmented Cadastral Map")
            summary_output = gr.Markdown()

    with gr.Row():
        geojson_download = gr.File(label="Download Legal-Grade GeoJSON (GIS Ready)")
        csv_download = gr.File(label="Download Attribute Records (CSV)")

    if SAMPLE_IMAGES:
        gr.Markdown("### Try a sample image")
        sample_gallery = gr.Gallery(
            value=SAMPLE_IMAGES,
            label="Select an image to run inference",
            columns=7,
            rows=1,
            height=150,
            object_fit="cover",
            allow_preview=True,
        )
        sample_download = gr.DownloadButton("Download selected sample")
        sample_gallery.select(
            fn=select_sample,
            outputs=[input_img, sample_download],
        ).then(
            fn=run_cpu,
            inputs=[input_img, conf_slider, area_slider],
            outputs=[output_img, summary_output, geojson_download, csv_download],
        )

    gr.HTML("""
    <section class="team-section">
        <h2>Team Engineer</h2>
        <p class="team-intro">A multidisciplinary team building a practical bridge between aerial imagery, AI segmentation, and GIS-ready land records.</p>
        <div class="team-grid">
            <div class="team-member"><strong>Rupak Kumar</strong><span>Team Leader · AI/ML and Database Management</span></div>
            <div class="team-member"><strong>Divyansh Tiwari</strong><span>AI/ML and Hosting</span></div>
            <div class="team-member"><strong>Vaibhav Goyal</strong><span>Full-Stack Integration</span></div>
            <div class="team-member"><strong>Ishaan Agarwal</strong><span>Frontend - UI/UX</span></div>
            <div class="team-member"><strong>Palak</strong><span>Backend</span></div>
            <div class="team-member"><strong>Pankaj</strong><span>System Design</span></div>
        </div>
    </section>
    """)

    submit_btn.click(
        fn=run_selected_device,
        inputs=[input_img, conf_slider, area_slider, device_selector],
        outputs=[output_img, summary_output, geojson_download, csv_download]
    )

if __name__ == "__main__":
    demo.launch()